Repository primakara-developers/portal-primakara, pull requests merged in 2018-12, with the labels that each got.

#75 adding text-decoration property and re-setting transition animation
  package-lock.json
  resources/assets/sass/pages/home/_subscription.scss
Labels: bug, enhancement, front-end

#76 Completed Header and banner section
  .gitignore
  public/images/workshop-photos.jpg
  resources/assets/images/workshop-photos.jpg
  resources/assets/js/app.js
  resources/assets/js/modules/MobileNav.js
  resources/assets/sass/config/_base.scss
  resources/assets/sass/config/_variable.scss
  resources/assets/sass/pages/home/_banner.scss
  resources/assets/sass/pages/home/main.scss
  resources/assets/sass/partials/_header.scss
  resources/assets/sass/partials/_mobile-nav.scss
  resources/assets/sass/partials/_site-header.scss
  resources/assets/sass/partials/main.scss
  resources/views/client/home.blade.php
  resources/views/client/partials/header.blade.php
  resources/views/layouts/clientLayout.blade.php
Labels: enhancement, front-end

#88 manage structure folders for Controllers and create new controller for index
  app/Http/Controllers/Client/HomeController.php
  app/Http/Controllers/Dashboard/AdminController.php
  app/Http/Controllers/Dashboard/CategoryController.php
  app/Http/Controllers/Dashboard/HeadlineController.php
  app/Http/Controllers/Dashboard/HomeController.php
  app/Http/Controllers/Dashboard/PostController.php
  routes/web.php
Labels: back-end, enhancement, feature

#90 edit routes/web.php
  app/Http/Controllers/Client/HomeController.php
  routes/web.php
Labels: back-end, enhancement, feature
