Repository primakara-developers/portal-primakara, pull requests merged in 2019-01, with the labels that each got.

#96 creating component for breadcrumb
  resources/assets/sass/pages/post-list/_breadcrumbs.scss
  resources/assets/sass/pages/post-list/main.scss
  resources/views/client/postList.blade.php
Labels: feature, front-end

#97 finish post-list in category page
  .gitignore
  resources/assets/sass/config/_variable.scss
  resources/assets/sass/pages/post-list/_post.scss
  resources/assets/sass/pages/post-list/main.scss
  resources/views/client/postList.blade.php
Labels: feature, front-end

#98 finish pagination section
  resources/assets/sass/pages/post-list/_pagination.scss
  resources/assets/sass/pages/post-list/main.scss
  resources/views/client/postList.blade.php
Labels: feature, front-end

#99 fix bug-truncate
  resources/assets/sass/pages/home/_informationsection.scss
Labels: bug, front-end

#101 Complete Navigation Bar
  public/images/icons/search.svg
  resources/assets/images/icons/search.svg
  resources/assets/js/modules/categoryListSetup.js
  resources/assets/js/modules/searchMobileSetup.js
  resources/assets/js/navigation-bar.js
  resources/assets/sass/config/_variable.scss
  resources/assets/sass/helper/_clearfix.scss
  resources/assets/sass/helper/main.scss
  resources/assets/sass/pages/post-list/_navigation-bar.scss
  resources/assets/sass/pages/post-list/main.scss
  resources/views/client/partials/header.blade.php
  resources/views/client/postList.blade.php
  webpack.mix.js
Labels: feature, front-end

#102 Setup post-detail
  resources/assets/sass/pages/main.scss
  resources/assets/sass/pages/post-detail/main.scss
  resources/views/client/postDetail.blade.php
  routes/web.php
Labels: front-end

#106 Finishing post list
  resources/assets/sass/pages/post-list/_breadcrumbs.scss
  resources/assets/sass/pages/post-list/_pagination.scss
  resources/assets/sass/pages/post-list/_post.scss
  resources/views/client/postList.blade.php
Labels: enhancement, front-end

#107 fix responsive in post section
  resources/assets/sass/pages/post-list/_post.scss
Labels: bug, front-end

#108 Add mockup post-detail
  public/images/mockup/post-detail-mockup.jpg
  routes/web.php
Labels: front-end

#116 Implement click outside category-list
  resources/assets/js/modules/categoryListSetup.js
Labels: enhancement, front-end

#117 change font-size margin and responsive
  resources/assets/sass/pages/post-list/_pagination.scss
Labels: bug, enhancement, front-end

#123 Complete Share Section
  public/images/icons/copy.svg
  public/images/icons/facebook.svg
  public/images/icons/line.svg
  public/images/icons/whatsapp.svg
  resources/assets/images/icons/copy.svg
  resources/assets/images/icons/facebook.svg
  resources/assets/images/icons/line.svg
  resources/assets/images/icons/whatsapp.svg
  resources/assets/sass/config/_variable.scss
  resources/assets/sass/pages/post-detail/_share.scss
  resources/assets/sass/pages/post-detail/main.scss
  resources/assets/sass/pages/post-list/_navigation-bar.scss
  resources/assets/sass/partials/_simple-tooltip.scss
  resources/assets/sass/partials/_site-header.scss
  resources/assets/sass/partials/main.scss
  resources/views/client/partials/paginator.blade.php
  resources/views/client/postDetail.blade.php
Labels: feature, front-end

#112 Rewrite Footer and UKM Section
  public/images/logo-gradient.png
  resources/assets/images/logo-gradient.png
  resources/assets/sass/_additional.scss
  resources/assets/sass/pages/home/_all.scss
  resources/assets/sass/pages/home/_ukm.scss
  resources/assets/sass/pages/home/main.scss
  resources/assets/sass/partials/_footer.scss
  resources/views/client/home.blade.php
Labels: feature, front-end

#126 Related posts
  resources/assets/sass/pages/post-detail/_related-posts.scss
  resources/assets/sass/pages/post-detail/main.scss
  resources/views/client/postDetail.blade.php
Labels: feature, front-end

#128 Cleanup project
  public/images/check.svg
  public/images/logo.jpg
  public/images/primakara-logo.svg
  public/images/primakara.jpg
  public/images/primakaradev.jpg
  public/images/primdev-logo.svg
  public/images/primdev-trans.png
  public/images/primdev.jpg
  public/images/scroll.png
  resources/assets/images/logo.jpg
  resources/assets/images/primakara-logo.svg
  resources/assets/images/primakara.jpg
  resources/assets/images/primakaradev.jpg
  resources/assets/images/primdev-logo.svg
  resources/assets/images/primdev-trans.png
  resources/assets/images/primdev.jpg
  resources/assets/sass/_additional.scss
  resources/assets/sass/app.scss
  resources/assets/sass/pages/home/_all.scss
  resources/assets/sass/pages/home/_information-section.scss
  resources/assets/sass/pages/home/main.scss
  resources/assets/sass/pages/post-detail/_post-detail.scss
  resources/assets/sass/pages/post-detail/_related-posts.scss
  resources/assets/sass/pages/post-detail/_share.scss
  resources/assets/sass/pages/post-list/_post.scss
  resources/assets/sass/pages/post-list/main.scss
  resources/assets/sass/partials/_breadcrumbs.scss
  resources/assets/sass/partials/_navigation-bar.scss
  resources/assets/sass/partials/_pagination.scss
  resources/assets/sass/partials/_site-header.scss
  resources/assets/sass/partials/main.scss
  resources/views/client/.fuse_hidden0000011800000001
  resources/views/client/home.blade.php
  resources/views/client/partials/breadcrumbs.blade.php
  resources/views/client/partials/footer.blade.php
  resources/views/client/partials/header.blade.php
  resources/views/client/partials/navigationBar.blade.php
  resources/views/client/partials/pagination.blade.php
  resources/views/client/postList.blade.php
  resources/views/layouts/clientLayout.blade.php
Labels: enhancement, front-end

#129 Post detail
  app/Http/Controllers/Client/SinglePageController.php
  resources/views/client/partials/navigationBar.blade.php
  resources/views/client/postDetail.blade.php
Labels: back-end, feature

#131 Fix/footer
  public/images/logo-gradient.svg
  public/images/p.svg
  resources/assets/images/logo-gradient.png
  resources/assets/images/logo-gradient.svg
  resources/assets/sass/partials/_footer.scss
  resources/views/client/home.blade.php
Labels: bug, front-end

#133 Fix bug information index
  resources/assets/sass/pages/home/_information-section.scss
  resources/views/client/home.blade.php
Labels: bug, front-end

#139 Change tooltip with toast
  package.json
  resources/assets/js/copy-to-clipboard.js
  resources/assets/sass/app.scss
  resources/assets/sass/pages/post-detail/_share.scss
  resources/assets/sass/partials/main.scss
  resources/assets/sass/vendor/main.scss
  resources/assets/sass/vendor/native-toast.scss
  resources/views/client/postDetail.blade.php
  resources/views/layouts/clientLayout.blade.php
  webpack.mix.js
  yarn.lock
Labels: bug, front-end

#141 Fix spacing content on 1150px
  resources/assets/sass/pages/home/_headline.scss
  resources/assets/sass/pages/home/_information-section.scss
  resources/assets/sass/pages/post-detail/_post-detail.scss
  resources/assets/sass/pages/post-detail/_related-posts.scss
  resources/assets/sass/pages/post-detail/_share.scss
  resources/assets/sass/pages/post-list/_post.scss
  resources/assets/sass/partials/_breadcrumbs.scss
  resources/assets/sass/partials/_footer.scss
  resources/assets/sass/partials/_navigation-bar.scss
  resources/assets/sass/partials/_pagination.scss
  resources/assets/sass/partials/_site-header.scss
Labels: bug, front-end
